[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.9.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-optional"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"